# Generated by Django 5.2.5 on 2025-08-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_auto_20250807_2347"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profiles"},
        ),
    ]
