# Generated by Django 5.2.5 on 2025-08-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0002_copy_data_from_old_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Adresses"},
        ),
        migrations.AlterModelOptions(
            name="letting",
            options={"verbose_name_plural": "Lettings"},
        ),
    ]
