name: CI

on:
  pull_request:
    branches: ["**"]
  push:
    branches-ignore: ["master"]

jobs:
  test-and-lint:
    name: Lint, tests & coverage (>=80%)
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "ci-secret-key"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1"
      DJANGO_SECURE_SSL_REDIRECT: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8

      - name: Django migrate (SQLite)
        run: |
          python manage.py migrate --noinput

      - name: Flake8
        run: |
          flake8 .

      - name: Pytest with coverage (fail under 80%)
        run: |
          pytest --maxfail=1 --disable-warnings -q \
            --cov=. --cov-report=xml --cov-report=term-missing --cov-fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
